#!/bin/bash
echo "--> Testing internet access"
ping=$(ping -4i 2 -c 4 1.1.1.1 | grep -oP "[0-9] received" | grep -oP "[0-9]")
if [ $ping == 0 ]; then
  echo "--> Changing MAC Address"
  macchanger
else
  echo "--> ${ping}/4 packets received"
fi
echo "--> Testing internet access (1/3 tries)"
ping=$(ping -4i 2 -c 4 1.1.1.1 | grep -oP "[0-9] received" | grep -oP "[0-9]")
if [ $ping == 0 ]; then
  echo "--> Changing MAC Address"
  macchanger
else
  echo "--> ${ping}/4 packets received"
  exit
fi
ping=$(ping -4i 2 -c 4 1.1.1.1 | grep -oP "[0-9] received" | grep -oP "[0-9]")
echo "--> Testing internet access (2/3 tries)"
if [ $ping == 0 ]; then
  echo "--> Changing MAC Address"
  macchanger
else
  echo "--> ${ping}/4 packets received"
  exit
fi
echo "--> Testing internet access (3/3 tries)"
ping=$(ping -4i 2 -c 4 1.1.1.1 | grep -oP "[0-9] received" | grep -oP>
if [ $ping == 0 ]; then
  echo "--> Error, still no internet access"
  exit
else
  echo "--> ${ping}/4 packets received"
  exit
fi
